Ensure navController.setGraph in AppMainActivity is not ran async
To fix crash for findNavController
java.lang.IllegalStateException: No current destination found. Ensure a navigation graph has been set for NavController...