Loading/saving Questionnaire Performance enhancements (#3782)
* Print Logs

* Inject CustomJsonParser to avoid new instance on every call

* Trigger pre-initialization of sdc's fhirPathEngine in background

to reduce time taken in initialize it when loading a questionnaire

* Launch T.updateFrom onto a background coroutine thread

Merging would happen in background, and update to db with the merged resource

* Apply spotless formatting

* Fix spotless formatting errors

* Launch post save tasks asynchronous to saving operation

Tasks such as generation of CarePlan, and CQL evaluation to happen
asynchronously after extracted resources are saved

* Revert "Launch post save tasks asynchronous to saving operation"

This reverts commit c05d0068f77f7eb3f205018a734b6c82f3f869b0.

* Cleanup and remove measureTime println statements

* Ensure navController.setGraph in AppMainActivity is not ran async

To fix crash for findNavController
java.lang.IllegalStateException: No current destination found. Ensure a navigation graph has been set for NavController...

* Disable CI quest timeouts

* Update and refactor handleQuestionnaireSubmission

* Fix engine tests errors

* Remove test listeners

* Fix failing tests in RulesFactoryTest

* Remove mockk lib from quest android tests

* Exclude instrumentation tests from jacocoReport

* Deleted commented lines

---------

Co-authored-by: Rkareko <47570855+Rkareko@users.noreply.github.com>